# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\t.;weather',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rweather.proto\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x8a\x01\n\rQueryResponse\x12*\n\tlocations\x18\x01 \x03(\x0b\x32\x17.QueryResponse.Location\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x1a>\n\x08Location\x12\r\n\x05title\x18\x01 \x01(\t\x12\x14\n\x0clocationType\x18\x02 \x01(\t\x12\r\n\x05woeid\x18\x03 \x01(\x04\"\x1f\n\x0eWeatherRequest\x12\r\n\x05woeid\x18\x01 \x01(\x04\"\xa2\x02\n\x0fWeatherResponse\x12)\n\x07weather\x18\x01 \x01(\x0b\x32\x18.WeatherResponse.Weather\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x1a\xd4\x01\n\x07Weather\x12\r\n\x05title\x18\x01 \x01(\t\x12\x14\n\x0clocationType\x18\x02 \x01(\t\x12\r\n\x05woeid\x18\x03 \x01(\x04\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\x14\n\x0cweatherState\x18\x05 \x01(\t\x12\x0f\n\x07minTemp\x18\x06 \x01(\x01\x12\x0f\n\x07maxTemp\x18\x07 \x01(\x01\x12\x11\n\twindSpeed\x18\x08 \x01(\x01\x12\x15\n\rwindDirection\x18\t \x01(\x01\x12\x13\n\x0b\x61irPressure\x18\n \x01(\x01\x12\x10\n\x08humidity\x18\x0b \x01(\x01\x32\x9b\x01\n\x0eWeatherService\x12(\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12+\n\x04Read\x12\x0f.WeatherRequest\x1a\x10.WeatherResponse\"\x00\x12\x32\n\tSubscribe\x12\x0f.WeatherRequest\x1a\x10.WeatherResponse\"\x00\x30\x01\x42\x0bZ\t.;weatherb\x06proto3'
)




_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=46,
)


_QUERYRESPONSE_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='QueryResponse.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='QueryResponse.Location.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locationType', full_name='QueryResponse.Location.locationType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woeid', full_name='QueryResponse.Location.woeid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=187,
)

_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='QueryResponse.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='QueryResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYRESPONSE_LOCATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=187,
)


_WEATHERREQUEST = _descriptor.Descriptor(
  name='WeatherRequest',
  full_name='WeatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='woeid', full_name='WeatherRequest.woeid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=220,
)


_WEATHERRESPONSE_WEATHER = _descriptor.Descriptor(
  name='Weather',
  full_name='WeatherResponse.Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='WeatherResponse.Weather.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locationType', full_name='WeatherResponse.Weather.locationType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woeid', full_name='WeatherResponse.Weather.woeid', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='WeatherResponse.Weather.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weatherState', full_name='WeatherResponse.Weather.weatherState', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minTemp', full_name='WeatherResponse.Weather.minTemp', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxTemp', full_name='WeatherResponse.Weather.maxTemp', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='windSpeed', full_name='WeatherResponse.Weather.windSpeed', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='windDirection', full_name='WeatherResponse.Weather.windDirection', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='airPressure', full_name='WeatherResponse.Weather.airPressure', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='WeatherResponse.Weather.humidity', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=513,
)

_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weather', full_name='WeatherResponse.weather', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='WeatherResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WEATHERRESPONSE_WEATHER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=513,
)

_QUERYRESPONSE_LOCATION.containing_type = _QUERYRESPONSE
_QUERYRESPONSE.fields_by_name['locations'].message_type = _QUERYRESPONSE_LOCATION
_WEATHERRESPONSE_WEATHER.containing_type = _WEATHERRESPONSE
_WEATHERRESPONSE.fields_by_name['weather'].message_type = _WEATHERRESPONSE_WEATHER
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['WeatherRequest'] = _WEATHERREQUEST
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {

  'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
    'DESCRIPTOR' : _QUERYRESPONSE_LOCATION,
    '__module__' : 'weather_pb2'
    # @@protoc_insertion_point(class_scope:QueryResponse.Location)
    })
  ,
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)
_sym_db.RegisterMessage(QueryResponse.Location)

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERREQUEST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherRequest)
  })
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), {

  'Weather' : _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
    'DESCRIPTOR' : _WEATHERRESPONSE_WEATHER,
    '__module__' : 'weather_pb2'
    # @@protoc_insertion_point(class_scope:WeatherResponse.Weather)
    })
  ,
  'DESCRIPTOR' : _WEATHERRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherResponse)
  })
_sym_db.RegisterMessage(WeatherResponse)
_sym_db.RegisterMessage(WeatherResponse.Weather)


DESCRIPTOR._options = None

_WEATHERSERVICE = _descriptor.ServiceDescriptor(
  name='WeatherService',
  full_name='WeatherService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=516,
  serialized_end=671,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='WeatherService.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='WeatherService.Read',
    index=1,
    containing_service=None,
    input_type=_WEATHERREQUEST,
    output_type=_WEATHERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='WeatherService.Subscribe',
    index=2,
    containing_service=None,
    input_type=_WEATHERREQUEST,
    output_type=_WEATHERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERSERVICE)

DESCRIPTOR.services_by_name['WeatherService'] = _WEATHERSERVICE

# @@protoc_insertion_point(module_scope)
